# name: sprawozdanie
# on: push
# jobs:
#   pdf:
#     runs-on: ubuntu-22.04
#     steps:
#       - run: pip install ipykernel scipy pint open_atmos_jupyter_utils matplotlib numpy
#       - uses: actions/checkout@v4
#       - run: sudo apt-get install texlive-xetex inkscape pandoc
#       - run: pip install nbconvert
#       - run: python -m nbconvert --to pdf --execute mpdata_2d_numpy_only.ipynb
#       - uses: actions/upload-artifact@v4 # @v3
#         with:
#           # name: sprawozdanie
#           # path: test.pdf
#           path: anim.gif

name: projekt
on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex inkscape pandoc libomp-dev
          pip install ipykernel scipy pint open_atmos_jupyter_utils matplotlib numpy nbconvert PyMPDATA tabulate

      - name: Execute notebook and generate PDF
        run: |
          python -m nbconvert --to pdf --execute project2.ipynb \
            --TagRemovePreprocessor.enabled=True \
            --TagRemovePreprocessor.remove_input_tags="hide_input"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: projekt
          path: |
            project2.pdf
